### ISSUE TITLE
Mount custom configuration files fail.

### ISSUE THREAD

**Issue by wanghongzhou** [bitnami/bitnami-docker-elasticsearch#103]
### Name and Version

bitnami/elasticsearch::8.2.2

### What steps will reproduce the bug?

Mount configuration files to /opt/bitnami/elasticsearch/config/my_elasticsearch.yml,If the file is empty, an error is reported at startup.

### What is the expected behavior?

This is explained in the tutorial https://hub.docker.com/r/bitnami/elasticsearch

`If you would rather extend than replace the default configuration with your settings, mount your custom configuration file at /opt/bitnami/elasticsearch/config/my_elasticsearch.yml.`

I should understand merge configuration, even if my configuration file is empty should not error.

### What do you see instead?

```
 elasticsearch 02:13:39.94 
elasticsearch    | elasticsearch 02:13:39.94 Welcome to the Bitnami elasticsearch container
elasticsearch    | elasticsearch 02:13:39.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
elasticsearch    | elasticsearch 02:13:39.94 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elasticsearch    | elasticsearch 02:13:39.94 
elasticsearch    | elasticsearch 02:13:39.94 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch    | warning: ignoring JAVA_HOME=/opt/bitnami/java; using ES_JAVA_HOME
elasticsearch    | elasticsearch 02:13:41.06 WARN  ==> Setting ELASTICSEARCH_IS_DEDICATED_NODE is disabled.
elasticsearch    | elasticsearch 02:13:41.06 WARN  ==> ELASTICSEARCH_NODE_ROLES and ELASTICSEARCH_NODE_TYPE will be ignored and Elasticsearch will asume all different roles.
elasticsearch    | elasticsearch 02:13:41.06 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch    | elasticsearch 02:13:41.08 INFO  ==> Custom configuration file detected, using it...
elasticsearch    | 
elasticsearch    | elasticsearch 02:13:41.12 INFO  ==> ** Elasticsearch setup finished! **
elasticsearch    | elasticsearch 02:13:41.13 INFO  ==> ** Starting Elasticsearch **
elasticsearch    | warning: ignoring JAVA_HOME=/opt/bitnami/java; using ES_JAVA_HOME
elasticsearch    | warning: ignoring JAVA_HOME=/opt/bitnami/java; using ES_JAVA_HOME
elasticsearch    | warning: ignoring JAVA_HOME=/opt/bitnami/java; using ES_JAVA_HOME
elasticsearch    | [2022-06-17T02:13:45,215][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [604d59d9554a] uncaught exception in thread [main]
elasticsearch    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.data' (/opt/bitnami/elasticsearch/data)
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    | Caused by: java.lang.IllegalStateException: Unable to access 'path.data' (/opt/bitnami/elasticsearch/data)
elasticsearch    |      at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:66) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:231) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:173) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.bootstrap.Security.configure(Security.java:120) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:229) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:358) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-8.2.2.jar:8.2.2]
elasticsearch    |      ... 6 more
elasticsearch    | Caused by: java.nio.file.AccessDeniedException: /opt/bitnami/elasticsearch/data
elasticsearch    |      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
elasticsearch    |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
elasticsearch    |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
elasticsearch    |      at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) ~[?:?]
```

**Comment by dgomezleon** [comment]
Hi @wanghongzhou ,

Thanks for the feedback. I was able to reproduce the error and I will work on fixing it.

**Comment by dgomezleon** [comment]
The issue is fixed now ([tag 8.2.3-debian-11-r2](https://github.com/bitnami/bitnami-docker-elasticsearch/releases/tag/8.2.3-debian-11-r2)).
