### ISSUE TITLE
Cannot install ingest-geoip

### ISSUE THREAD

**Issue by solstarz** [bitnami/bitnami-docker-elasticsearch#53]
While trying to install ingest-geoip with the env variable ELASTICSEARCH_PLUGINS, it fails.

This is the error im receiving, this is in the container:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
Exception in thread "main" java.nio.file.FileSystemException: /opt/bitnami/elasticsearch/config/ingest-geoip: Operation not permitted
```
Looks like rights issue.
Is there a workaround for this?

Thanks in advance.

**Comment by rafariossaa** [comment]
Hi @solstarz,
   Could you try to reinstall it following our [guide](https://docs.bitnami.com/general/apps/elasticsearch/configuration/install-plugins/) ? I hope that will fix the permission issues.

Thanks forehand,
Rafael Rios,

**Comment by solstarz** [comment]
Hi @rafariossaa, 

Thanks for your reply.
I've checked the guide, but i cannot run that in the docker container.

Is there maybe an other way?

Thanks in advance.

JP,

**Comment by rafariossaa** [comment]
Hi @solstarz,
  Sorry, the guide is not for containers.

  I cherry picked several plugins and I had no problems installing then through the env var, but with the ingest-geoip plugin the error appears.

  I tried to find a workaround for this issue but and I could not find one.

  I will add this issue to our backlog and we will look how to fix it.

Best regards,
Rafael Rios.

**Comment by juan131** [comment]
I think it's exactly the same problem reported at https://github.com/bitnami/bitnami-docker-elasticsearch/issues/50

**Comment by XBeg9** [comment]
Any updates here? getting the same error.

```
* Classname: org.elasticsearch.ingest.geoip.IngestGeoIpPlugin
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
Exception in thread "main" java.nio.file.FileSystemException: /opt/bitnami/elasticsearch/config/ingest-geoip: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Posix.setOwners(UnixFileAttributeViews.java:252)
	at sun.nio.fs.UnixFileAttributeViews$Posix.setOwner(UnixFileAttributeViews.java:274)
	at org.elasticsearch.plugins.InstallPluginCommand.setOwnerGroup(InstallPluginCommand.java:919)
	at org.elasticsearch.plugins.InstallPluginCommand.installConfig(InstallPluginCommand.java:892)
	at org.elasticsearch.plugins.InstallPluginCommand.installPluginSupportFiles(InstallPluginCommand.java:826)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:807)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:776)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

**Comment by rafariossaa** [comment]
Hi @XBeg9 ,

  No, the tasks still in our backlog.
  Anyway there is a workaround for the #50 issue that maybe fix this issue too:
  You have to open a shell in the container and run:
`chown -R 1001:0 /opt/bitnami/elasticsearch/config/ /opt/bitnami/elasticsearch/plugins/`
  or modify the docker file and add:
`RUN chown -R 1001:0 /opt/bitnami/elasticsearch/config/ /opt/bitnami/elasticsearch/plugins/`
  under the ENV block

**Comment by juan131** [comment]
Hi everyone,

We just released a new revision of ES including a fix that allow users to install plugins (such as `ingest-geoip`).

As a consequence, this image doesn't work with K8s distributions which use non-root users with arbitrary UIDs. 

More info at: https://github.com/bitnami/bitnami-docker-elasticsearch/blob/master/README.md#685-debian-9-r0-685-ol-7-r1-742-debian-9-r10-742-ol-7-r27

**Comment by marcosbc** [comment]
Closing since this seems to be resolved.
