### ISSUE TITLE
help / Add storage key

### ISSUE THREAD

**Issue by AmirHo3ein13** [bitnami/bitnami-docker-elasticsearch#64]
**Description**

I want to add s3 keys to deployment for elasticsearch 6.4.2 but I couldn't find elasticsearch-keystore in this project files. Is there any way to do it?

**Comment by marcosbc** [comment]
Hi @AmirHo3ein13, the `elasticsearch-keystore` binary is available in the PATH:

```bash
$ which elasticsearch-keystore
/opt/bitnami/elasticsearch/bin/elasticsearch-keystore
```

I verified it is available in the Bitnami Elasticsearch 6.4.2 container image (id `a042a1f92e8b`).

Find the usage instructions here: https://www.elastic.co/guide/en/elasticsearch/reference/current/secure-settings.html

**Comment by AmirHo3ein13** [comment]
Thank you @marcosbc for your response. I've seen this instruction but as I am using helm and bitnami chart to deploy elasticsearch, I need these settings to apply each time deployment restarts (or in other words, image is pulled or container is rebuilt). When I add my keys to elasticsearch and restart deployment, settings are gone.

In `setup.sh` in this project, there was a function that adds plugins by checking env vars (`elasticsearch_install_plugins()` in `libelasticsearch.sh`) that installs plugins each time deployment restarts. But I couldn't find any code that do this for keys

**Comment by marcosbc** [comment]
Hi @AmirHo3ein13, you are right about that. I have created an internal task for implementing this, but unfortunately cannot provide an ETA for when we will start.

In the meantime, you could always fork the bitnami/bitnami-docker-elasticsearch repository and add a similar section than the one currently for plugins, to create/load the keystore, and add proper keys. If you do, it would be great if you send a PR!

**Comment by AmirHo3ein13** [comment]
Thank @marcosbc. I'll do that.

**Comment by AmirHo3ein13** [comment]
Hi again. I was trying to do as you said but when I try to install `repository-s3` plugin in the container built from this repository (6/debian-9) using this command:  
```
elasticsearch-plugin install -v -b repository-s3
```
it throws this error:
```
Exception in thread "main" java.nio.file.FileSystemException: /opt/bitnami/elasticsearch/config/repository-s3: Operation not permitted
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Posix.setOwners(UnixFileAttributeViews.java:252)
        at sun.nio.fs.UnixFileAttributeViews$Posix.setOwner(UnixFileAttributeViews.java:274)
        at org.elasticsearch.plugins.InstallPluginCommand.setOwnerGroup(InstallPluginCommand.java:928)
        at org.elasticsearch.plugins.InstallPluginCommand.installConfig(InstallPluginCommand.java:901)
        at org.elasticsearch.plugins.InstallPluginCommand.installPluginSupportFiles(InstallPluginCommand.java:835)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:816)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:785)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```
I even tried fixing it by changing permissions like `USER` (in `Dockerfile`) or `$ELASTICSEARCH_DAEMON_USER` and `$ELASTICSEARCH_DAEMON_GROUP` (in `libelasticsearch.sh`) to elasticsearch, root, 1001 or 1000 but none of them worked! 
In the case when `USER` is not set, `$ELASTICSEARCH_DAEMON_USER` is elasticsearch and `$ELASTICSEARCH_DAEMON_GROUP` is root, I solved the error but when I deployed it on the server, `GET _cat/indices` shows this error:
```
curl: (7) Failed to connect to elasticsearch-coordinating-only.default.svc.cluster.local port 9200: Connection refused
command terminated with exit code 7
```

**Comment by marcosbc** [comment]
Hi @AmirHo3ein13, unfortunately there's an open ticket on Elastic's side with respect to that issue: https://github.com/elastic/elasticsearch/issues/40969.

In order to workaround this, you could try installing the plugin as a root user, and then change the permissions to a proper value. But this requires to modify the Dockerfile.

Another alternative is to disable the non-root approach, by removing the "USER 1001" from the Dockerfile.
That should be enough to get it working, however I just tried and it failed due to recent changes. I've created an internal task for fixing the Elasticsearch container running as root, I'll try to have a look at it in the next couple of days but cannot give any guarantee it will be fixed.
