### ISSUE TITLE
docker-composer up not working, exited with code 1

### ISSUE THREAD

**Issue by ishan-biztech** [bitnami/bitnami-docker-elasticsearch#85]
**Description**

When running `docker-compose up` command getting below error:

```
➜  cakephp-test-project git:(elasticsearch) ✗ docker-compose up                    
Starting cakephp-test-project_elasticsearch_1_482e1581fc0f ... done
Attaching to cakephp-test-project_elasticsearch_1_482e1581fc0f
elasticsearch_1_482e1581fc0f |  11:05:45.27 
elasticsearch_1_482e1581fc0f |  11:05:45.28 Welcome to the Bitnami elasticsearch container
elasticsearch_1_482e1581fc0f |  11:05:45.28 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
elasticsearch_1_482e1581fc0f |  11:05:45.28 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elasticsearch_1_482e1581fc0f |  11:05:45.28 
elasticsearch_1_482e1581fc0f |  11:05:45.28 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch_1_482e1581fc0f |  11:05:45.33 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch_1_482e1581fc0f |  11:05:45.37 INFO  ==> Custom configuration file detected, using it...
elasticsearch_1_482e1581fc0f | 
elasticsearch_1_482e1581fc0f |  11:05:45.41 INFO  ==> ** Elasticsearch setup finished! **
elasticsearch_1_482e1581fc0f |  11:05:45.44 INFO  ==> ** Starting Elasticsearch **
elasticsearch_1_482e1581fc0f | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch_1_482e1581fc0f | OpenJDK 64-Bit Server VM warning: UseAVX=2 is not supported on this CPU, setting it to UseAVX=1
elasticsearch_1_482e1581fc0f | [2020-09-14T11:05:48,542][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [42c4df419985] uncaught exception in thread [main]
elasticsearch_1_482e1581fc0f | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.node.Node.<init>(Node.java:299) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  ... 6 more
elasticsearch_1_482e1581fc0f | Caused by: java.nio.file.AccessDeniedException: /bitnami/elasticsearch/data/nodes
elasticsearch_1_482e1581fc0f |  at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
elasticsearch_1_482e1581fc0f |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
elasticsearch_1_482e1581fc0f |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
elasticsearch_1_482e1581fc0f |  at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
elasticsearch_1_482e1581fc0f |  at java.nio.file.Files.createDirectory(Files.java:689) ~[?:?]
elasticsearch_1_482e1581fc0f |  at java.nio.file.Files.createAndCheckIsDirectory(Files.java:796) ~[?:?]
elasticsearch_1_482e1581fc0f |  at java.nio.file.Files.createDirectories(Files.java:782) ~[?:?]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:273) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:206) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:270) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f |  ... 6 more
cakephp-test-project_elasticsearch_1_482e1581fc0f exited with code 1
```

**Steps to reproduce the issue:**

1. Create `docker-compose.yml` file
2. Add below contents in `docker-compose.yml` file

```yml
version: '2'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.56.0/24

services:
  elasticsearch:
    image: 'bitnami/elasticsearch:6-debian-10'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - './elasticsearch_data:/bitnami/elasticsearch/data'
    networks:
      - default
```
3. Run `docker-compose up`

**Describe the results you received:**

```
Starting cakephp-test-project_elasticsearch_1_482e1581fc0f ... done
Attaching to cakephp-test-project_elasticsearch_1_482e1581fc0f
elasticsearch_1_482e1581fc0f |  11:05:45.27 
elasticsearch_1_482e1581fc0f |  11:05:45.28 Welcome to the Bitnami elasticsearch container
elasticsearch_1_482e1581fc0f |  11:05:45.28 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-elasticsearch
elasticsearch_1_482e1581fc0f |  11:05:45.28 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-elasticsearch/issues
elasticsearch_1_482e1581fc0f |  11:05:45.28 
elasticsearch_1_482e1581fc0f |  11:05:45.28 INFO  ==> ** Starting Elasticsearch setup **
elasticsearch_1_482e1581fc0f |  11:05:45.33 INFO  ==> Configuring/Initializing Elasticsearch...
elasticsearch_1_482e1581fc0f |  11:05:45.37 INFO  ==> Custom configuration file detected, using it...
elasticsearch_1_482e1581fc0f | 
elasticsearch_1_482e1581fc0f |  11:05:45.41 INFO  ==> ** Elasticsearch setup finished! **
elasticsearch_1_482e1581fc0f |  11:05:45.44 INFO  ==> ** Starting Elasticsearch **
elasticsearch_1_482e1581fc0f | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch_1_482e1581fc0f | OpenJDK 64-Bit Server VM warning: UseAVX=2 is not supported on this CPU, setting it to UseAVX=1
elasticsearch_1_482e1581fc0f | [2020-09-14T11:05:48,542][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [42c4df419985] uncaught exception in thread [main]
elasticsearch_1_482e1581fc0f | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.node.Node.<init>(Node.java:299) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	... 6 more
elasticsearch_1_482e1581fc0f | Caused by: java.nio.file.AccessDeniedException: /bitnami/elasticsearch/data/nodes
elasticsearch_1_482e1581fc0f | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
elasticsearch_1_482e1581fc0f | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
elasticsearch_1_482e1581fc0f | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
elasticsearch_1_482e1581fc0f | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
elasticsearch_1_482e1581fc0f | 	at java.nio.file.Files.createDirectory(Files.java:689) ~[?:?]
elasticsearch_1_482e1581fc0f | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:796) ~[?:?]
elasticsearch_1_482e1581fc0f | 	at java.nio.file.Files.createDirectories(Files.java:782) ~[?:?]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:273) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:206) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:270) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.12.jar:6.8.12]
elasticsearch_1_482e1581fc0f | 	... 6 more
cakephp-test-project_elasticsearch_1_482e1581fc0f exited with code 1
```

**Describe the results you expected:**

It should run properly, without any exception or exit code 1.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:48 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 16
  Running: 0
  Paused: 0
  Stopped: 16
 Images: 65
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.18.0-25-generic
 Operating System: Ubuntu 18.10
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 11.22GiB
 Name: sys29
 ID: KAJY:US6V:IYJK:RERY:EGRA:CWHN:PID5:LM7O:IOU2:TRXL:IODQ:W2G2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by dani8art** [comment]
Hi @ishan-biztech , thanks for opening the issue. 

Our containers are prepared to be run as non-root user so that you would need to modify the permissions of your local directory or use a docker volume instead. Please, try to execute the following


```console
$ sudo chmod -R g+wr elasticsearch_data/
```

Otherwise, you also can use docker volume instead 

```yaml
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
```

**Comment by ishan-biztech** [comment]
Thanks @dani8art. I've solved it by creating a new volume called `elasticsearch_data`.
